# Generated by Django 3.0.8 on 2020-07-28 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='cart_items',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('img', models.ImageField(upload_to='pics')),
                ('price', models.IntegerField()),
                ('quantity', models.ImageField(upload_to='')),
            ],
        ),
    ]
