# Generated by Django 3.0.8 on 2020-07-29 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommers', '0003_cart_items_email_user_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart_items',
            name='quantity',
            field=models.IntegerField(),
        ),
    ]
