# Generated by Django 3.0.8 on 2020-07-30 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommers', '0004_auto_20200729_1709'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart_items',
            name='quantity',
        ),
    ]
