# Generated by Django 3.0.8 on 2020-08-02 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommers', '0005_remove_cart_items_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart_items',
            name='quantity',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
